version: "3"

services:

  apache:
    build:
      context: ./
      dockerfile: ./docker/apache/Dockerfile
    depends_on:
      - mysql
    ports:
      - "4000:80"

  php-fpm:
    build:
      context: ./
      dockerfile: ./docker/php-fpm/Dockerfile
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: omardb
      MYSQL_USER: omar
      MYSQL_PASSWORD: 123

volumes:
  db:
